function ddyn = dyn_turn_5(tdummy,in2,udummy)
%DYN_TURN_5
%    DDYN = DYN_TURN_5(TDUMMY,IN2,UDUMMY)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-May-2023 15:18:52

err_u_sum = in2(18,:);
h = in2(3,:);
u = in2(4,:);
t2 = u.*-4.0;
ddyn = [u.*cos(h);u.*sin(h);0.0;t2+t2.*(err_u_sum.*(7.0./1.0e+1)+1.3e+1./1.0e+1);0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;1.0];
end
