function ddyn = dyn_turn_1_lo2hi(tdummy,in2,udummy,Tdummy)
%DYN_TURN_1_LO2HI
%    DDYN = DYN_TURN_1_LO2HI(TDUMMY,IN2,UDUMMY,Tdummy)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-May-2023 15:18:49

Fx_error = in2(15,:);
Fy_error = in2(14,:);
brake_time = in2(13,:);
err_h_sum = in2(17,:);
err_r_sum = in2(16,:);
err_u_sum = in2(18,:);
h = in2(3,:);
h0 = in2(19,:);
p_u = in2(11,:);
p_y = in2(12,:);
r0 = in2(9,:);
t = in2(20,:);
t0 = in2(10,:);
u = in2(4,:);
u0 = in2(7,:);
v0 = in2(8,:);
x = in2(1,:);
y = in2(2,:);
t2 = t.*pi;
t4 = p_y./2.0;
t3 = cos(t2);
t6 = p_y.*t3.*(-1.0./2.0);
t7 = t4+t6;
ddyn = [x;y;h;u;-t7.*(u.^2.*2.189696155436131e-3-1.67e+2./1.0e+2);t7;u0;v0;r0;t0;p_u;p_y;brake_time;Fy_error;Fx_error;err_r_sum;err_h_sum;err_u_sum;h0;t];
end
