function ddyn = dyn_turn_3(tdummy,in2,udummy)
%DYN_TURN_3
%    DDYN = DYN_TURN_3(TDUMMY,IN2,UDUMMY)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-May-2023 15:18:50

Fx_error = in2(15,:);
Fy_error = in2(14,:);
err_h_sum = in2(17,:);
err_r_sum = in2(16,:);
err_u_sum = in2(18,:);
h = in2(3,:);
h0 = in2(19,:);
p_u = in2(11,:);
p_y = in2(12,:);
r = in2(6,:);
t = in2(20,:);
u = in2(4,:);
v = in2(5,:);
t2 = cos(h);
t3 = sin(h);
t4 = p_u.*4.0;
t5 = r.*2.0;
t6 = u.*4.0;
t7 = -p_y;
t8 = t-2.0;
t14 = err_h_sum.*1.005102352581729;
t15 = err_r_sum.*1.005102352581729;
t9 = -t6;
t10 = t8.*pi;
t17 = t14+t15+4.002551176290865;
t11 = cos(t10);
t12 = sin(t10);
t13 = p_y.*t11;
t16 = t5+t7+t13;
et1 = Fy_error.*1.26984126984127e-3+p_y.*1.839022334597556-r.*3.678044669195112-t13.*1.839022334597556+((r.*4.847676e+5-v.*2.9028e+5).*1.573254670599803e-3)./u-r.*u-t16.*t17.*1.839022334597556;
et2 = p_y.*t12.*pi.*9.19511167298778e-1;
ddyn = [t2.*u-t3.*v;t3.*u+t2.*v;r;Fx_error./1.575e+3+t4+t9+(err_u_sum.*(3.28e+2./3.75e+2)+1.624380952380952).*(t4+t9);et1+et2;Fy_error.*(-5.1023525817293e-4)+p_y-t5+t7.*t11-t16.*t17+(p_y.*t12.*pi)./2.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;(p_y.*(-1.0./2.0)+r+t13./2.0).^2;(h+h0+t7-(p_y.*t)./2.0+(p_y.*sin(t.*pi))./(pi.*2.0)).^2;(p_u-u).^2;0.0;1.0];
end
